// Testing out some pipeline stuff

pipeline{
	

	stages{
		agent any
		stage('setup'){
			agent any
			steps{
				script{
					env.MINOR_VERSION = sh(returnStdout: true, script: "git rev-list --all --count").trim()
					currentBuild.setDisplayName("${env.MINOR_VERSION}")
				}
			}
		}

		stage('dockerize'){
			agent{
				docker{
					image 'node:16-alpine'
			}
	}
			steps{
				script{
					sh 'node --version'
				}
			}
		}

		stage('test 3'){
			agent any
			
			steps{
				echo 'test stage 3'
			}
		}
	}
}