// Testing out some pipeline stuff

pipeline{
	agent{
		docker{
			image 'node:16-alpine'
		}
	}

	stages{
		stage('setup'){
			steps{
				script{
					env.MINOR_VERSION = sh(returnStdout: true, script: "git rev-list --all --count").trim()
					currentBuild.setDisplayName("${env.MINOR_VERSION}")
				}
			}
		}

		stage('dockerize'){
			steps{
				script{
					sh 'node --version'
				}
			}
		}

		stage('test 3'){
			steps{
				echo 'test stage 3'
			}
		}
	}
}