// Testing out some pipeline stuff

pipeline{
	agent none

	environment{
		sonarKey = credentials('sonar_project_key')
		sonarToken = credentials('sonar_token_1')
		
	}

	stages{
		
		stage('setup'){
			agent any
			steps{
				script{
					env.MINOR_VERSION = sh(returnStdout: true, script: "git rev-list --all --count").trim()
					currentBuild.setDisplayName("${env.MINOR_VERSION}")
					echo "${env.MINOR_VERSION}"
				}
			}
		}

		stage('dockerize'){
			agent{
				docker{
					image 'sonarsource/sonar-scanner-cli'
					
				}
			}
			steps{
				script{
					
					sh '''
						pwd
						export SONAR_TOKEN=${SONAR_TOKEN_A}
						sonar-scanner \
						-Dsonar.organization=yeehha \
						-Dsonar.projectKey=${sonarKey} \
						-Dsonar.sources=. \
						-Dsonar.host.url=https://sonarcloud.io \
						-Dsonar.login=${sonarToken}

					'''
				}
			}
		}

		// stage('test 3'){
		// 	agent{
		// 		docker{
		// 			image 'docker:latest'
		// 		}
		// 	}	
			
		// 	steps{
		// 		script{
		// 			sh "docker images"
		// 		}
		// 	}
		// }
	}
}